/*INSERT INTO ROLES (user_role) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES (user_role) VALUES ('ROLE_STUDENT');

INSERT INTO DEPARTMENTS (name) VALUES('ART_HISTORY');
INSERT INTO DEPARTMENTS (name) VALUES('BIOLOGICAL_SCIENCES');
INSERT INTO DEPARTMENTS (name) VALUES('BUSINESS');
INSERT INTO DEPARTMENTS (name) VALUES('CHEMISTRY');
INSERT INTO DEPARTMENTS (name) VALUES('COMPUTER_SCIENCE');
INSERT INTO DEPARTMENTS (name) VALUES('ECONOMICS');
INSERT INTO DEPARTMENTS (name) VALUES('HUMANITIES');
INSERT INTO DEPARTMENTS (name) VALUES('LINGUISTICS');
INSERT INTO DEPARTMENTS (name) VALUES('MATHEMATICS');
INSERT INTO DEPARTMENTS (name) VALUES('MUSIC');
INSERT INTO DEPARTMENTS (name) VALUES('PHILOSOPHY');
INSERT INTO DEPARTMENTS (name) VALUES('PHYSICS');
INSERT INTO DEPARTMENTS (name) VALUES('POLITICAL_SCIENCE');
INSERT INTO DEPARTMENTS (name) VALUES('PSYCHOLOGY');
INSERT INTO DEPARTMENTS (name) VALUES('SOCIOLOGY');
INSERT INTO DEPARTMENTS (name) VALUES('VISUAL_ARTS');*/