package dev.proqa.studentmanagementsystem.model.enumeration;

public enum Departments {
    ART_HISTORY, BIOLOGICAL_SCIENCES, BUSINESS, CHEMISTRY, COMPUTER_SCIENCE, ECONOMICS, HUMANITIES, LINGUISTICS, MATHEMATICS,
    MUSIC, PHILOSOPHY, PHYSICS, POLITICAL_SCIENCE, PSYCHOLOGY, SOCIOLOGY, VISUAL_ARTS,
}
